# Site settings
title: Björn Holtvogt
description: Björn Holtvogt
baseurl: ""
url: "localhost:3000"

# User settings
user_title: Software Engineer
user_description: Passionate about backend development, distributed systems, and building scalable, intelligent software.
username: Björn Holtvogt
email: bjoern.holtvogt@gmail.com
linkedin_username: bjoernholtvogt
github_username: holtvogt

# Google analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
