# Site settings
title: Björn Holtvogt
description: Passionate about backend development, distributed systems, and building scalable, intelligent software.
baseurl: ""
url: "localhost:3000"

# User settings
user_title: Software Engineer
user_description: |
  I'm a Master's student in Computer Science at KIT, specializing in software engineering and cognitive systems (AI). My focus is on backend development, distributed computing, and AI-powered applications, with a deep interest in building scalable and high-performance software systems.
  
  With experience at IBM, Cisco, and Porsche, I've built a strong foundation in backend engineering, distributed systems, real-time data processing, and AI-driven applications. My technical background includes building high-performance backend systems, optimizing large-scale data workflows, and integrating machine learning models for intelligent automation.
  
  I'm passionate about the intersection of software engineering and AI, exploring how distributed systems, and scalable architectures can enhance performance and efficiency. Whether working on backend services, cloud-native solutions, or data-driven applications, I enjoy solving complex problems and building software that scales.
username: Björn Holtvogt
email: bjoern.holtvogt@gmail.com
linkedin_username: bjoernholtvogt
github_username: holtvogt

# Google analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
